#!/usr/bin/env bash
# Wire an already-created Cloudflare Tunnel to the opencode-web service.
#
#   sudo ./finish-tunnel.sh opencode.lorite.eu [tunnel-name]
#
# Run this AFTER the two interactive steps, which need your browser and must run as you,
# not root (they write to ~/.cloudflared):
#
#     cloudflared tunnel login
#     cloudflared tunnel create opencode
#
# Everything after that is mechanical, and this does it: the credentials JSON lands in
# YOUR home, but cloudflared.service runs as root — so the credentials are copied to
# /etc/cloudflared (root:root 0600, the right home for a system service's secret) and the
# config points there. Hand-writing that path is what produced
# "Tunnel credentials file '/root/.cloudflared/<id>.json' doesn't exist".
set -euo pipefail

DOMAIN="${1:-}"
TUNNEL="${2:-opencode}"
OWNER="${OPENCODE_OWNER:-lorite}"
PORT="${OPENCODE_PORT:-4096}"
ETC="/etc/cloudflared"

die()  { echo "ERROR: $*" >&2; exit 1; }
step() { echo; echo "==> $*"; }

[[ $EUID -eq 0 ]] || die "run with sudo: sudo $0 <domain> [tunnel-name]"
[[ -n "$DOMAIN" ]] || die "usage: sudo $0 <domain> [tunnel-name]"
command -v cloudflared >/dev/null || die "cloudflared not installed — run setup-hardened.sh first"

OWNER_HOME="$(getent passwd "$OWNER" | cut -d: -f6)"
[[ -d "$OWNER_HOME/.cloudflared" ]] \
    || die "$OWNER_HOME/.cloudflared not found — run 'cloudflared tunnel login' as $OWNER first"

# ── 1. Resolve the tunnel and its credentials ───────────────────────────────────
step "Resolving tunnel '$TUNNEL'"
TUNNEL_ID="$(runuser -u "$OWNER" -- cloudflared tunnel list --output json 2>/dev/null \
    | python3 -c "
import json,sys
try: rows = json.load(sys.stdin)
except Exception: sys.exit(0)
for r in rows:
    if r.get('name') == '$TUNNEL':
        print(r['id']); break
" || true)"
[[ -n "$TUNNEL_ID" ]] || die "tunnel '$TUNNEL' not found — run: cloudflared tunnel create $TUNNEL   (as $OWNER)"

CREDS="$OWNER_HOME/.cloudflared/$TUNNEL_ID.json"
[[ -f "$CREDS" ]] || die "credentials file missing: $CREDS"
echo "    $TUNNEL -> $TUNNEL_ID"

# ── 2. Install credentials where a system service should keep them ─────────────
step "Installing credentials to $ETC"
install -d -m 0755 -o root -g root "$ETC"
install -m 0600 -o root -g root "$CREDS" "$ETC/$TUNNEL_ID.json"
echo "    $ETC/$TUNNEL_ID.json (root:root 0600)"

# ── 3. Config ───────────────────────────────────────────────────────────────────
step "Writing $ETC/config.yml"
cat > "$ETC/config.yml" <<EOF
# Generated by finish-tunnel.sh. The tunnel dials OUT to Cloudflare, so nothing listens
# on a public interface — the opencode-web service stays bound to 127.0.0.1.
tunnel: $TUNNEL_ID
credentials-file: $ETC/$TUNNEL_ID.json

ingress:
  - hostname: $DOMAIN
    service: http://127.0.0.1:$PORT
  # Anything else that reaches this tunnel is not ours.
  - service: http_status:404
EOF
chmod 0644 "$ETC/config.yml"
cloudflared --config "$ETC/config.yml" tunnel ingress validate \
    || die "cloudflared rejected the ingress config"
echo "    validated"

# ── 4. DNS route ────────────────────────────────────────────────────────────────
# Needs the origin certificate in $OWNER's ~/.cloudflared, so it runs as $OWNER.
step "Routing $DOMAIN at the tunnel"
if runuser -u "$OWNER" -- cloudflared tunnel route dns "$TUNNEL" "$DOMAIN" 2>&1 | tee /tmp/cf-route.log; then
    echo "    routed"
elif grep -qi "already exists\|record with that host" /tmp/cf-route.log; then
    echo "    already routed — leaving it"
else
    die "DNS route failed — see /tmp/cf-route.log"
fi
rm -f /tmp/cf-route.log

# ── 5. Service ──────────────────────────────────────────────────────────────────
step "Starting cloudflared"
[[ -f /etc/systemd/system/cloudflared.service ]] || cloudflared service install
systemctl daemon-reload
systemctl enable cloudflared >/dev/null 2>&1 || true
systemctl restart cloudflared
sleep 8
systemctl is-active --quiet cloudflared \
    || { journalctl -u cloudflared -n 20 --no-pager; die "cloudflared did not start"; }
echo "    running"

# ── 6. Verify end to end ────────────────────────────────────────────────────────
step "Verifying"
systemctl is-active --quiet opencode-web || die "opencode-web is not running"
LOCAL="$(curl -s -o /dev/null -w '%{http_code}' "http://127.0.0.1:$PORT/app" || true)"
[[ "$LOCAL" == "401" ]] || die "backend returned $LOCAL locally, expected 401"
echo "    backend: 401 unauthenticated (correct)"

echo "    waiting for the tunnel to publish..."
for _ in $(seq 1 12); do
    PUB="$(curl -s -o /dev/null -w '%{http_code}' --max-time 10 "https://$DOMAIN/app" || true)"
    [[ "$PUB" != "000" && -n "$PUB" ]] && break
    sleep 5
done
echo "    https://$DOMAIN/app -> HTTP ${PUB:-no response}"

cat <<EOF

────────────────────────────────────────────────────────────────────────────
Tunnel is up. What that HTTP code means:

  401  reaching OpenCode's own Basic Auth. Working, but Cloudflare Access is
       NOT in front of it yet — do the dashboard step below before relying on it.
  302  Cloudflare Access is in front and redirecting to login. This is the goal.
  404  the tunnel is up but the hostname does not match the ingress rule.
  000  DNS has not propagated yet; retry in a minute.

Last step — Cloudflare dashboard, Zero Trust -> Access -> Applications:
  * Add a self-hosted application for $DOMAIN
  * Settings -> Authentication: add Google as an identity provider first
  * Policy: Allow, include -> Emails -> your address
  * Session duration: 24 h default

Then check from a private window: https://$DOMAIN should show the Cloudflare
login page, NOT OpenCode.
────────────────────────────────────────────────────────────────────────────
EOF
