#!/usr/bin/env bash
# Build a working headless obsidian-clipper CLI, reproducibly.
#
# Why this exists: plain upstream `main` DOES NOT WORK. It builds fine and then emits
# empty notes (frontmatter only, no title, no content), because the Node polyfill banner
# is missing `navigator`/`getComputedStyle` and because Defuddle is handed an Element
# where it expects a Document. `npm i -g obsidian-clipper` would silently give you that
# broken build. The fixes live in patches/ here and are applied on top of a PINNED
# upstream commit, so the result is deterministic rather than "whatever main is today".
#
# Upstream has these bugs open; a PR was closed as the CLI being work-in-progress, so we
# carry the patches ourselves rather than waiting for them to land.
#
# Usage:
#   ./build-cli.sh              # build the pinned commit + patches (deterministic)
#   ./build-cli.sh --latest     # build today's origin/main instead, to see if the
#                               # patches still apply / are still needed
#   ./build-cli.sh --check      # verify the existing build still produces real output
#
# Env overrides: OBSIDIAN_CLIPPER_DIR, OBSIDIAN_CLIPPER_COMMIT

set -euo pipefail

REPO="https://github.com/obsidianmd/obsidian-clipper.git"
BUILD_DIR="${OBSIDIAN_CLIPPER_DIR:-$HOME/.local/share/obsidian-clipper-cli}"
# Pinned upstream commit the patches are known to apply to (main @ 2026-07-27).
PIN="${OBSIDIAN_CLIPPER_COMMIT:-ec27f8b}"
PATCH_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/patches"
WRAPPER="$HOME/.local/bin/obsidian-clipper-cli"
# Smoke-test target: small, stable, and thematically ours.
SMOKE_URL="https://docs.activitywatch.net/en/latest/getting-started.html"
# Unpatched builds emit ~115 bytes (frontmatter only). Real output is >1 KB.
MIN_BYTES=600

mode="pinned"
[ "${1:-}" = "--latest" ] && mode="latest"
[ "${1:-}" = "--check" ] && mode="check"

smoke_test() {
    local out
    out=$(node "$BUILD_DIR/dist/cli.cjs" "$SMOKE_URL" \
        -t "$BUILD_DIR/src/utils/fixtures/templates/minimal.json" 2>/dev/null || true)
    local bytes=${#out}
    if [ "$bytes" -lt "$MIN_BYTES" ]; then
        echo "SMOKE TEST FAILED: only $bytes bytes (expected >= $MIN_BYTES)." >&2
        echo "That is the signature of an unpatched build producing empty notes." >&2
        return 1
    fi
    echo "Smoke test OK: $bytes bytes of real content."
}

if [ "$mode" = "check" ]; then
    [ -f "$BUILD_DIR/dist/cli.cjs" ] || { echo "No build at $BUILD_DIR/dist/cli.cjs" >&2; exit 1; }
    smoke_test
    exit $?
fi

if [ ! -d "$BUILD_DIR/.git" ]; then
    echo "Cloning $REPO -> $BUILD_DIR"
    git clone --quiet "$REPO" "$BUILD_DIR"
fi

cd "$BUILD_DIR"
git fetch --quiet origin

if [ "$mode" = "latest" ]; then
    target=$(git rev-parse origin/main)
    echo "Building LATEST origin/main ($(git rev-parse --short "$target"))"
else
    target="$PIN"
    echo "Building pinned commit $PIN"
fi

# Detached checkout + hard clean: the patches are the only source of local change, so the
# tree must start exactly at upstream or `git apply` will conflict on a re-run.
git checkout --quiet --detach "$target"
git reset --quiet --hard "$target"
git clean -qfd -e node_modules -e dist

shopt -s nullglob
patches=("$PATCH_DIR"/*.patch)
shopt -u nullglob
if [ ${#patches[@]} -eq 0 ]; then
    echo "No patches found in $PATCH_DIR" >&2
    exit 1
fi

for p in "${patches[@]}"; do
    if git apply --check "$p" 2>/dev/null; then
        git apply "$p"
        echo "  applied $(basename "$p")"
    else
        echo "  FAILED to apply $(basename "$p")" >&2
        if [ "$mode" = "latest" ]; then
            echo "  (upstream moved: either the bug was fixed, or the patch needs a refresh)" >&2
        fi
        exit 1
    fi
done

# Upstream's package-lock.json is internally inconsistent (a transitive mismatch,
# @emnapi/wasi-threads 1.2.2 vs 1.2.3), so `npm ci` refuses to run. Fall back to
# `npm install`, which resolves it. It rewrites package-lock.json, but the hard reset
# above restores the tree on every run, so this stays repeatable.
if ! npm ci --silent >/dev/null 2>&1; then
    echo "  npm ci rejected upstream's lockfile; using npm install"
    npm install --silent >/dev/null
fi
npm run build:cli >/dev/null
echo "Built $BUILD_DIR/dist/cli.cjs"

smoke_test

mkdir -p "$(dirname "$WRAPPER")"
cat > "$WRAPPER" <<EOF
#!/usr/bin/env bash
# Generated by dotfiles tools/lorite/obsidian-clipper/build-cli.sh — do not edit.
exec node "$BUILD_DIR/dist/cli.cjs" "\$@"
EOF
chmod 0755 "$WRAPPER"
echo "Wrapper -> $WRAPPER"
